### ISSUE TITLE
Fix repository URL

### ISSUE THREAD

**Issue by c31ck** [Crosscheck/projectify#19]
After the switch to the oneagency group in gitlab, the repository URL in the didi config is wrong. For example:
set :repository,  "git@gitlab.crosscheck.be:crosscheck/projectname"

should be
set :repository,  "git@gitlab.crosscheck.be:oneagency/projectname"

**Comment by c31ck** [comment]
Pull request: https://github.com/Crosscheck/projectify-extra-files/pull/4

**Comment by klaasvw** [comment]
Merged
