### ISSUE TITLE
Replace admin_views

### ISSUE THREAD

**Issue by matthiasm11** [Crosscheck/projectify#22]
The module https://www.drupal.org/project/admin_views replaces the default Drupal pages like /admin/content by editable views. Those views aren't exportable in features, so now we have to clone the admin_views_node view and disable the original admin_views_node. The cloned version can be edited and exported to features.

Solution: don't use admin_views, but create a default feature which contains those views (not only admin_views_node, but also for files, users...). This feature should be included in the makefile of website_core. (and thus be installed automatically by Projectify)

**Comment by kimkennof-dp** [comment]
Admin views is just a default provided module.

Any project specific setup should be done per project, and not in our standardised setup?

**Comment by kimkennof-dp** [comment]
9 out of 10 times we will not be required to override these views...

**Comment by kimkennof-dp** [comment]
Algeron will create a functional / technical analysis of this and perhaps also implement it later.

**Comment by kimkennof-dp** [comment]
We can not simply switch to a custom feature for this functionality, as "admin_views" also provides a views Access plugin to "pipe" the access requirements from the system paths, as well as a System Display plugin so you can override system paths with a view.

We can however create a custom feature, containing both View plugins, as well as our customized admin overview views. (a complete fork of "Admin_views", set up as a feature module)

One could then change the views and export them to the feature.

Downsides:

- Losing contrib support for "Admin_Views"
- Need to maintain the functionality throughout time / patches / sec-updates.

Upsides:

- Provide custom admin content overviews

Examples: 

- Add a language filter to Node overview. (i18n sites)

**Comment by kimkennof-dp** [comment]
It seems we didn't do our homework properly...

The File Entity module already provides an example on how to override Admin Views provided views in your own custom module.

Please see "File_Entity" module for an example on how to implement.
