### ISSUE TITLE
Bind ocelot to TAG instead of HEAD of omega branch

### ISSUE THREAD

**Issue by rob-bar** [Crosscheck/projectify#23]
We are about to do some huge work on ocelot, this means that if this projectify keeps up with a branch it will use the incomplete work we commit on that branch.
Can you bind the clone of the repo to a tag instead of the HEAD of the omega branch.
This is the tag:
https://github.com/Crosscheck/Ocelot/releases/tag/v.0.1.3.om

**Comment by kimkennof-dp** [comment]
Hey Robbie,

I think Klaas has closed this issue with a pull request on 19-06. He parses the latest release information from Github, and then reads out the "latest_tag". This most likely contains something "v0.1.3.nd" where "nd" gets stripped / replaced by "om". These ensures we are using the Omega Branch of Ocelot.

The rest is OK.

**Comment by kimkennof-dp** [comment]
Is this issue still actual?

**Comment by rob-bar** [comment]
No, can be closed
